### ISSUE TITLE
Make a new release with 49438b7 commit

### ISSUE THREAD

**Issue by jidhay** [RedHatQE/requestbin#1]
The library doesn't work in release 0.2 due to addition to new json attributes in response.
The commit 49438b7 correct the issue. However this correction wasn't released.
Please make a new release with the correction.

**Comment by dparalen** [comment]
jidhay, thanks for pointing out!
I've just uploaded a new release to Pipy[1], please reopen the issue if it doesn't work for you.

Cheers,
milan

[1] https://pypi.python.org/pypi?:action=display&name=requestbin&version=0.3

**Comment by jidhay** [comment]
Work like a charm. Thank you for your reactivity.
